# Generated by Django 5.2.6 on 2025-09-27 08:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_requests', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='servicerequest',
            name='assigned_field_worker',
            field=models.ForeignKey(blank=True, help_text='Field worker assigned to this service request', limit_choices_to={'is_approved': True, 'role': 'field_worker'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_service_requests', to=settings.AUTH_USER_MODEL),
        ),
    ]
